#pragma once

// syntax errors
#define ERR_MEMORY_ALLOCATION_FAILED "Memory allocation failed\n"
#define ERR_EXPECTED_PROGRAM "Syntax error: expected 'program' at %d:%d\n"
#define ERR_EXPECTED_IDENTIFIER_AFTER_PROGRAM "Syntax error: expected identifier after 'program' at %d:%d\n"
#define ERR_EXPECTED_SEMICOLON_AFTER_PROGRAM_IDENTIFIER "Syntax error: expected ';' after program identifier at %d:%d\n"
#define ERR_EXPECTED_BLOCK_AFTER_PROGRAM_DECLARATION "Syntax error: expected block after program declaration at %d:%d\n"
#define ERR_EXPECTED_DOT_AFTER_PROGRAM_BLOCK "Syntax error: expected '.' after program block at %d:%d\n"
#define ERR_EXPECTED_IDENTIFIER_AFTER_VAR "Syntax error: expected identifier after 'var' at %d:%d\n"
#define ERR_EXPECTED_COLON_OR_COMMA "Syntax error: expected ':' or ',' at %d:%d\n"
#define ERR_EXPECTED_TYPE_AFTER_COLON "Syntax error: expected type after ':' at %d:%d\n"
#define ERR_EXPECTED_SEMICOLON "Syntax error: expected ';' at %d:%d\n"
#define ERR_EXPECTED_COMMA_OR_COLON "Syntax error: expected ',' or ':' at %d:%d\n"
#define ERR_EXPECTED_IDENTIFIER_AFTER_COMMA "Syntax error: expected identifier after ',' at %d:%d\n"
#define ERR_EXPECTED_BEGIN "Syntax error: expected 'begin' at %d:%d\n"
#define ERR_EXPECTED_STATEMENT_AFTER_BEGIN "Syntax error: expected statement after 'begin' at %d:%d\n"
#define ERR_EXPECTED_END "Syntax error: expected 'end' at %d:%d\n"
#define ERR_INVALID_COMMAND "Syntax error: invalid command '%s' at %d:%d\n"
#define ERR_EXPECTED_IF "Syntax error: expected 'if' at %d:%d\n"
#define ERR_EXPECTED_EXPRESSION_AFTER_IF "Syntax error: expected expression after 'if' at %d:%d\n"
#define ERR_EXPECTED_THEN "Syntax error: expected 'then' at %d:%d\n"
#define ERR_EXPECTED_STATEMENT_AFTER_THEN "Syntax error: expected statement after 'then' at %d:%d\n"
#define ERR_EXPECTED_STATEMENT_AFTER_ELSE "Syntax error: expected statement after 'else' at %d:%d\n"
#define ERR_EXPECTED_WHILE "Syntax error: expected 'while' at %d:%d\n"
#define ERR_EXPECTED_EXPRESSION_AFTER_WHILE "Syntax error: expected expression after 'while' at %d:%d\n"
#define ERR_EXPECTED_DO "Syntax error: expected 'do' at %d:%d\n"
#define ERR_EXPECTED_STATEMENT_AFTER_DO "Syntax error: expected statement after 'do' at %d:%d\n"
#define ERR_EXPECTED_IDENTIFIER "Syntax error: expected identifier at %d:%d\n"
#define ERR_EXPECTED_ASSIGNMENT_OPERATOR "Syntax error: expected ':=' after identifier at %d:%d\n"
#define ERR_EXPECTED_EXPRESSION_AFTER_ASSIGNMENT "Syntax error: expected expression after ':=' at %d:%d\n"
#define ERR_EXPECTED_EXPRESSION_AFTER_OPERATOR "Syntax error: expected expression after '%s' at %d:%d\n"
#define ERR_EXPECTED_TERM_AFTER_OPERATOR "Syntax error: expected term after '%s' at %d:%d\n"
#define ERR_EXPECTED_FACTOR_AFTER_OPERATOR "Syntax error: expected factor after '%s' at %d:%d\n"
#define ERR_INVALID_NUMBER "Syntax error: invalid number '%s' at %d:%d\n"
#define ERR_EXPECTED_EXPRESSION_OR_SEMICOLON "Syntax error: expected expression or ';' at %d:%d\n"
#define ERR_EXPECTED_EXPRESSION_AFTER_OPEN_PAREN "Syntax error: expected expression after '(' at %d:%d\n"
#define ERR_EXPECTED_CLOSE_PAREN "Syntax error: expected ')' at %d:%d\n"
#define ERR_INVALID_FACTOR "Syntax error: invalid factor '%s' at %d:%d\n"
#define ERR_NO_TOKENS_TO_PARSE "No tokens to parse\n"